name: planning_csmf
description: Application de planning pour le CSMF Paris
publish_to: 'none'
version: 1.0.1+5

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.3
  
  # State management
  provider: ^6.1.2
  
  # HTTP & API
  http: ^1.2.2
  
  # Local storage
  shared_preferences: ^2.5.4
  
  # Utils
  intl: ^0.20.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/logo_csmf.jpg
